config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about'=> "homes#about", as: "homes_about"
  get 'search/search', as: "search"
  devise_for :users
  resources :users, only:[:show, :index, :edit, :update] do
    resource :relationships, only:[:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :books, only:[:show, :index, :create, :edit, :update, :destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(key, search)
    case search
    when "完全一致"
      Book.where("title LIKE ? OR body LIKE ?", key, key)
    when "部分一致"
      Book.where("title LIKE ? OR body LIKE ?", "%#{key}%" , "%#{key}%")
    when "前方一致"
      Book.where("title LIKE ? OR body LIKE ?", "#{key}%" , "#{key}%")
    when "後方一致"
      Book.where("title LIKE ? OR body LIKE ?", "%#{key}" , "%#{key}")
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: "follower"
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: "following"

  validates :name, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def self.search(key, search)
    case search
    when "完全一致"
      User.where("name LIKE ? OR introduction LIKE ?", key, key)
    when "部分一致"
      User.where("name LIKE ? OR introduction LIKE ?", "%#{key}%" , "%#{key}%")
    when "前方一致"
      User.where("name LIKE ? OR introduction LIKE ?", "#{key}%" , "#{key}%")
    when "後方一致"
      User.where("name LIKE ? OR introduction LIKE ?", "%#{key}" , "%#{key}")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book_detail = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(comment_params)
    @book_comment.book_id = @book_detail.id
    @book_comment.save
    @comments = @book_detail.book_comments
  end

  def destroy
    @book_detail = Book.find(params[:book_id])
    @book_comment = BookComment.find_by(id: params[:id], book_id: params[:book_id])
    @book_comment.destroy
    @comments = Book.find(params[:book_id]).book_comments
  end

  private
  def comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_new_book, only:[:show, :index]

  def show
    @book_detail = Book.find(params[:id])
    @user = @book_detail.user
    @book_comment = BookComment.new
    @comments = @book_detail.book_comments
  end

  def index
    @user = current_user
    @books = Book.all
  end

  def create
    @book = current_user.books.new(book_params)
    if @book.save
      redirect_to book_path(@book)
      flash[:notice] = "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render "books/index"
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice] = "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path

  end

  private
  def book_params
    params.require(:book).permit(:user_id, :title, :body)
  end

  def set_new_book
    @book = Book.new
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: params[:book_id])
    @favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: params[:book_id])
    @favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    model = params[:model]
    key = params[:key]
    search = params[:search]

    if model == "Book"
      @results = Book.search(key, search)
    elsif model == "User"
      @results = User.search(key, search)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_new_book

  def show
    @user = User.find(params[:id])
  end

  def index
    @user = current_user
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:notice] = "You have updated user successfully."
    else
      render :edit
    end
  end
  
  def follows
    user = User.find(params[:id])
    @follows = user.followings
  end
  
  def followers
    user = User.find(params[:id])
    @followers = user.followers
  end


  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def set_new_book
    @book = Book.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment.html.erb
<div>
  <table>
    <tbody>
      <% comments.each do |comment| %>
        <tr id="comment_<%= comment.id %>">
          <td>
            <%= link_to user_path(comment.user) do %>
              <%= attachment_image_tag comment.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
              <p><%= comment.user.name %></p>
            <% end %>
          </td>
          <td><%= comment.comment %></td>
          <% if comment.user == current_user %>
            <td><%= link_to "destroy", book_book_comment_path(comment.book, comment), remote: true, method: :delete, class: "btn btn-sm btn-danger" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/book_comments/create.js.erb
$(".count").html("コメント数：<%= @book_detail.book_comments.count %>");
$(".comments").html("<%= j( render 'book_comments/comment', book: @book_detail, book_comment: @book_comment, comments: @comments) %>");
$(".form-control").val("");

app/views/book_comments/destroy.js.erb
$(".count").html("コメント数：<%= @book_detail.book_comments.count %>");
$(".comments").html("<%= j(render "book_comments/comment", book: @book_detail, book_comment: @book_comment, comments: @comments) %>");

app/views/books/_books.html.erb
<h2>Books</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
        <td id="favorite-btn_<%= book.id %>">
          <%= render "favorites/favorite", book:book %>
        </td>
        <td>コメント数：<%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_new.html.erb
<h2 class="mt-3">New book</h2>
<div class="form-group">
  <%= form_with model: book, local: true do |f| %>
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: "form-control mb-3" %>
    <%= f.label :body, "Opinion" %>
    <%= f.text_area :body, class: "form-control mb-3" %>
    <%= f.submit class: "btn btn-success" %>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mx-auto">
      <%= render "layouts/error", model:@book %>
      <h2>Editing Book</h2>
      <div class="form-group">
        <%= form_with model: @book, local: true do |f| %>
          <%= f.label :title, "Title" %>
          <%= f.text_field :title, class: "form-control mb-3" %>
          <%= f.label :body, "Opinion" %>
          <%= f.text_area :body, class: "form-control mb-3" %>
          <%= f.submit class: "btn btn-success" %>
        <% end %>
      </div>
      <%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <%= render "layouts/error", model:@book %>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user:@user %>
      <%= render "books/new", book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render "books/books", books:@books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user:@user %>
      <%= render "books/new", book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book_detail.user) do %>
                <%= attachment_image_tag @book_detail.user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
                <p><%= @book_detail.user.name %></p>
              <% end %>
            </td>
            <td><%= link_to @book_detail.title, book_path(@book_detail) %></td>
            <td><%= @book_detail.body %></td>
            <% if @book_detail.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book_detail), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book_detail), class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
            <% else %>
              <td class="favorite-btn"><%= render "favorites/favorite", book:@book_detail %></td>
              <td class="count">コメント数：<%= @book_detail.book_comments.count %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div class="comments">
        <%= render "book_comments/comment", book: @book_detail, book_comment: @book_comment, comments: @comments %>
      </div>
      <div>
        <%= form_with(model: [@book_detail, @book_comment]) do |f| %>
          <%= f.text_area :comment, rows: "5", class: "form-control" %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), remote: true, method: :delete, style: "color: red;" do %>
    ♥<%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), remote: true, method: :post, style: "color: blue;" do %>
    ♥<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite-btn_<%= @book.id %>, .favorite-btn").html("<%= j(render 'favorites/favorite', book:@book) %>");

app/views/favorites/destroy.js.erb
$("#favorite-btn_<%= @book.id %>, .favorite-btn").html("<%= j(render 'favorites/favorite', book:@book) %>");

app/views/homes/about.html.erb
<div class="text-center">
  <h1>welcome to <strong><i class="fas fa-book"></i>Bookers</strong>!</h1>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="col-6 mx-auto">
    <h1>welcome to <i class="fas fa-book"></i>Bookers !!</h1>
    <p>In <strong><i class="fas fa-book"></i>Bookers</strong>,</p>
    <p>you can share and exchange your opinions , inpressions , and emotions</p>
    <p>about various books!</p>
    <div class="mx-5">
      <%= link_to "Log in", new_user_session_path, class: "btn btn-sm btn-info btn-block mb-3" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-sm btn-success btn-block" %>
    </div>
  </div>
</div>

app/views/search/_form.html.erb
<% if user_signed_in? %>
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :key %>
    <%= f.select :model, ["Book", "User"] %>
    <%= f.select :search, ["完全一致","部分一致","前方一致","後方一致"] %>
    <%= f.submit "検索" %>
  <% end %>
<% end %>

app/views/search/search.html.erb
  <% if @results.any? %>
    <% if params[:model] == "Book" %>
      <%= render "books/books", books:@results %>
    <% else %>
      <%= render "users/index", users:@results %>
    <% end %>
  <% else %>
    <p>検索結果は0件</p>
  <% end %>

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40" %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td>
          <% unless user == current_user %>
            <% if user.followed_by?(current_user) %>
              <%= link_to "フォローをはずす", user_relationships_path(user), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "100x100" %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th><%= link_to user.followings.count, follows_user_path(user) %></th>
    </tr>
    <tr>
      <th>followers</th>
      <th><%= link_to user.followers.count, followers_user_path(user) %></th>
    </tr>
  </tbody>
</table>
<% if user == current_user %>
  <%= link_to edit_user_path(user), class: "btn btn-sm btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
<% else %>
  <% if user.followed_by?(current_user) %>
    <%= link_to "フォローをはずす", user_relationships_path(user), class: "btn btn-sm btn-info", method: :delete %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user), class: "btn btn-sm btn-success", method: :post %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mx-auto">
      <%= render "layouts/error", model:@user %>
      <h2>User info</h2>
      <div class="form-group">
        <%= form_with model: @user, local: true do |f| %>
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control mb-3" %>
          <%= f.label :profile_image, "Image" %>
          <%= f.attachment_field :profile_image, class: "mb-3 d-block" %>
          <%= f.label :introduction, "Introduction" %>
          <%= f.text_area :introduction, class: "form-control mb-3" %>
          <%= f.submit class: "btn btn-secondary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<% if @followers.any? %>
  <%= render "users/index", users: @followers %>
<% else %>
 <p>ユーザーはいません</p>
<% end %>

app/views/users/follows.html.erb
<h2>Follow Users</h2>
<% if @follows.any? %>
  <%= render "users/index", users: @follows %>
<% else %>
 <p>ユーザーはいません</p>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user:@user %>
      <%= render "books/new", book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render "users/index", users:@users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user:@user %>
      <%= render "books/new", book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render "books/books", books:@user.books %>
    </div>
  </div>
</div>