config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about'=> "homes#about", as: "homes_about"
  get 'search/search', as: "search"
  devise_for :users
  resources :users, only:[:show, :index, :edit, :update] do
    resource :relationships, only:[:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :books, only:[:show, :index, :create, :edit, :update, :destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(key, search)
    case search
    when "完全一致"
      Book.where("title LIKE ? OR body LIKE ?", key, key)
    when "部分一致"
      Book.where("title LIKE ? OR body LIKE ?", "%#{key}%" , "%#{key}%")
    when "前方一致"
      Book.where("title LIKE ? OR body LIKE ?", "#{key}%" , "#{key}%")
    when "後方一致"
      Book.where("title LIKE ? OR body LIKE ?", "%#{key}" , "%#{key}")
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: "follower"
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: "following"

  validates :name, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def self.search(key, search)
    case search
    when "完全一致"
      User.where("name LIKE ? OR introduction LIKE ?", key, key)
    when "部分一致"
      User.where("name LIKE ? OR introduction LIKE ?", "%#{key}%" , "%#{key}%")
    when "前方一致"
      User.where("name LIKE ? OR introduction LIKE ?", "#{key}%" , "#{key}%")
    when "後方一致"
      User.where("name LIKE ? OR introduction LIKE ?", "%#{key}" , "%#{key}")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_new_book, only:[:show, :index]

  def show
    @book_detail = Book.find(params[:id])
    @user = @book_detail.user
    @book_comment = BookComment.new
    @comments = @book_detail.book_comments
  end

  def index
    @user = current_user
    @books = Book.all
  end

  def create
    @book = current_user.books.new(book_params)
    if @book.save
      redirect_to book_path(@book)
      flash[:notice] = "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render "books/index"
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice] = "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path

  end

  private
  def book_params
    params.require(:book).permit(:user_id, :title, :body)
  end

  def set_new_book
    @book = Book.new
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: params[:book_id])
    @favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: params[:book_id])
    @favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    model = params[:model]
    key = params[:key]
    search = params[:search]

    if model == "Book"
      @results = Book.search(key, search)
    elsif model == "User"
      @results = User.search(key, search)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_new_book

  def show
    @user = User.find(params[:id])
  end

  def index
    @user = current_user
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:notice] = "You have updated user successfully."
    else
      render :edit
    end
  end
  
  def follows
    user = User.find(params[:id])
    @follows = user.followings
  end
  
  def followers
    user = User.find(params[:id])
    @followers = user.followers
  end


  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def set_new_book
    @book = Book.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error.html.erb
<% if model.errors.any? %>
  <div class="error-messages", style="color: red;">
    <h3><%= pluralize(model.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-5">
  <p class="text-center">CopyRight Infratop.inc</p>
</footer>

app/views/layouts/_header.html.erb
<header class="mb-3">
  <nav class="navbar navbar-expand bg-dark">
    <div class="container">
      <%= link_to "Bookers", root_path, class: "navbar-brand text-light" %>
      <% if user_signed_in? %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to user_path(current_user), class: "nav-link text-light" do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to  users_path, class: "nav-link text-light" do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to books_path, class: "nav-link text-light" do %>
              <i class="fas fa-book-open"></i> Books
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, class: "nav-link text-light", method: :delete do %>
              <i class="fas fa-sign-out-alt"></i> logout
            <% end %>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link text-light" do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to homes_about_path, class: "nav-link text-light" do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
              <i class="fas fa-user-plus"></i> sign up
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link text-light" do %>
              <i class="fas fa-sign-in-alt"></i> login
            <% end %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
  <div class="text-center mt-2">
    <%= render "search/form" %>
  </div>
  <span class="text-success"><%= notice %></span>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>